# exemplo deu um netlify.toml
[build]
<<<<<<< HEAD
  base = "botafogo/guia-LandingPage"
=======
>>>>>>> 3ca54e5264a764d55d0c9e56ce68c0a846721065
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200